### PR TITLE
add missing use statement

### PR DESCRIPTION
**Pull request by ziali088**
tried using this module but was met with a 'perhaps you forgot to load' error for this package.

could you please merge/release this soon? thanks

### CODE REVIEW

**Comment by timlegge** [comment]
weird.  I have been testing that particular function a lot lately.  I will give it a quick look tonight.  Did you have XML::Generator installed?  Which OS version and perl version?

No issue merging it just weird I have not seen the issue

**Comment by ziali088** [comment]
I'm on Ubuntu 16.04 and Perl 5.16.3

I seem to have had xml generator installed prior to installing this module as I installed net saml2 in a local directory.

Would be nice to have it out by tomorrow as I'll be installing it at work for production after successful testing :)

Thank
Ali

**Comment by timlegge** [comment]
lol - will try but I have curling tonight :-).  I should be able to do it
though

Tim

**Comment by ziali088** [comment]
You go curl Tim, you go curl.

**Review by timlegge — APPROVED** [review]

**Comment by timlegge** [comment]
Released should be available for installation anytime now

**Comment by ziali088** [comment]
Thank you

**Pull request merged**
